version: '2'

services:
    default:
        image: nginx:stable
        container_name: default
        networks:
            - traefik
        labels:
            traefik.http.routers.default.rule: HostRegexp(`{subdomain:.*}.izu.re`)
            traefik.http.routers.default.priority: 1
            traefik.http.routers.default.middlewares: default-middleware
            traefik.http.routers.default.entrypoints: websecure
            traefik.http.routers.default.tls: true
            traefik.http.routers.default.tls.certresolver: letsEncrypt

            traefik.http.middlewares.default-middleware.errors.status: 400-599
            traefik.http.middlewares.default-middleware.errors.service: error-pages-service
            traefik.http.middlewares.default-middleware.errors.query: /{status}
            
            traefik.http.services.error-pages-service.loadbalancer.server.port: 80
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
            - ./html:/var/www/html
networks:
    traefik:
        external:
            name: traefik_gateway
