version: '2'

services:
  traefik:
    image: traefik:latest
    restart: always
    labels:
      traefik.enable: false
    ports:
      - 80:80
      - 443:443
      - 8080:8080
      - 25565:25565
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/traefik.yml
      - ./dynamic.yml:/dynamic.yml
      - ./acme.json:/etc/traefik/acme/acme.json
    networks:
      - gateway
    env_file: .env
    container_name: traefik

networks:
  gateway:
    driver: bridge
