api:
  insecure: true

providers:
  docker: {}

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"

  websecure:
    address: ":443"

certificatesResolvers:
  letsEncrypt:
    acme:
      email: me@izu.re
      storage: /etc/traefik/acme/acme.json
      dnsChallenge:
        # used during the challenge
        provider: cloudflare
