version: '2'

services:
    aud:
        build:
            context: aud_server/
            dockerfile: ./Dockerfile
        container_name: aud
        networks:
            - traefik
        labels:
            traefik.http.routers.aud.rule: Host(`aud.izu.re`)
            traefik.http.routers.aud.tls: true
            traefik.http.routers.aud.tls.certresolver: letsEncrypt
            traefik.http.routers.aud.entrypoints: websecure

        volumes:
            - /data/aud/myNotebooks:/root/AuD/jupyter/myNotebooks
networks:
    traefik:
        external:
            name: traefik_gateway
